"""
add-other-column

Revision ID: 2eea6870986a
Revises: 322cf4f0ed51
Create Date: 2016-03-05 14:24:34.003835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eea6870986a'
down_revision = '322cf4f0ed51'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('other', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee', 'other')
    ### end Alembic commands ###
